  - name: add Chrome repository keys from URLs
    apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub
    become: yes

  - name: Install Spotify APT key
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=BBEBDCB318AD50EC6865090613B00F1FD2C19886
    become: yes

  - name: Install Redis dotdeb keyserver
    apt_key: url=http://www.dotdeb.org/dotdeb.gpg
    become: yes

  - name: install required repositories
    apt_repository: repo="{{item}}" state=present
    with_items:
      - deb http://dl.google.com/linux/chrome/deb/ stable main
      - deb http://repository.spotify.com stable non-free
      - ppa:webupd8team/atom
      - deb http://packages.dotdeb.org squeeze all
      - deb-src http://packages.dotdeb.org squeeze all
    become: yes

  - name: install packages
    apt: name={{item}} state=present update_cache=true autoremove=true
    with_items:
      - atom
      - google-chrome-stable
      - spotify-client
      - redis-server
    become: yes

  -  name: install DEB packages
     apt: deb={{item}}
     with_items:
       - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
     become: yes
