- name: Download terraform
  get_url: url=https://releases.hashicorp.com/terraform/0.7.2/terraform_0.7.2_linux_amd64.zip dest=/tmp/terraform_0.7.2.zip
  tags: terraform

- name: Unarchive terraform
  unarchive: src=/tmp/terraform_0.7.2.zip dest=/usr/local/share creates=/usr/local/share/terraform
  become: yes
  tags: terraform

- name: Create symlink for terraform
  file: src=/usr/local/share/terraform dest=/usr/local/bin/terraform mode=0777 state=link
  become: yes
  tags: terraform
